# Generated by Django 2.0 on 2021-11-04 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0002_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
