# Generated by Django 2.0 on 2021-11-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0005_auto_20211105_1213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='attendance',
            name='payment_method',
            field=models.CharField(choices=[('Wave Money', 'Wave Money'), ('KBZ Pay', 'KBZ Pay'), ('Mobile Banking', 'Mobile Banking')], max_length=200, null=True),
        ),
    ]
