# Generated by Django 2.0 on 2021-11-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0006_auto_20211105_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dutation',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
