# Generated by Django 2.0 on 2021-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0007_course_dutation'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
