# Generated by Django 2.0 on 2021-11-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0008_course_course_pic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendence',
        ),
    ]
