# Generated by Django 2.0 on 2021-11-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0010_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
