# Generated by Django 2.0 on 2021-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycourse', '0011_teacher_teacher_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
